### ISSUE TITLE
可使用掘金行情端口替代tushare行情

### ISSUE THREAD

**Issue by waiwaic** [vnpy/vnpy_gm#5]
可使用掘金提供的端口替换tushare端口，如果需要我非常乐意提供PR
ts.get_realtime_quotes to gm.api.current
ts.pro_api.query to get_instrumentinfos

与一些typeing的错误修复

**Comment by vnpy** [comment]
欢迎发PR贡献代码。

行情方面之前跟掘金确认过，目前作为API的gmtrade接口是没有提供的，只有作为策略框架的gm库才有，所以之前用了tushare。
